//@ flow

export const MUST_BE_INSIDE_REDUX_FORM = (component: string): string =>
  `${component} must be inside a component decorated with reduxForm()`

export const PROP_NOT_SPECIFIED = (component: string, prop: string): string =>
  `No "${prop}" prop was specified in <${component} />`

export const INVALID_PROP = (
  component: string,
  prop: string,
  mustBe?: string
): string =>
  `Invalid prop "${prop}" supplied to <${component} />. Must be either an array of strings or the fields array generated by FieldArray.`
