export const validateNameProp = (prop: string, component: string) => {
  if (!prop) {
    return new Error(`No "names" prop was specified <${component} />`)
  }
  if (!Array.isArray(prop) && !prop._isFieldArray) {
    return new Error(
      `Invalid prop "names" supplied to <${component} />. Must be either an array of strings or the fields array generated by FieldArray.`
    )
  }
}
